---
driver:
  name: vagrant
  customize:
    memory: 2048


provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[consensus-prediction::_common]
      - recipe[chef-bioinf-worker::openms]
      - recipe[chef-bioinf-worker::crux]
      - recipe[chef-bioinf-worker::tandem]
      - recipe[chef-bioinf-worker::blast]
      - recipe[chef-bioinf-worker::omssa]
      - recipe[chef-cuneiform::default]
      - recipe[consensus-prediction::default]
    attributes:
