---
driver:
  name: vagrant
  customize:
    memory: 2048


provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[consensus-prediction::_common]
      - recipe[consensus-prediction::default]
    attributes:
