---
driver:
  name: vagrant
  customize:
    memory: 4096


provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[consensus-prediction::_common]
      - recipe[chef-bioinf-worker::openms]
      - recipe[chef-cuneiform::default]
      - recipe[consensus-prediction::default]
    attributes:
